title: Filip Jelic
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Author Settings
author: Filip Jelic 
author-img: filip-jelic.jpg
about-author: Software engineer with a great passion for javascript. Currently working in the biotechnology industry. # add description
twitter: flipioo 
facebook: filip.jelic
github: flipio 
linkedin: filip-jelic-ff
email: jelic.filip@gmail.com

# Disqus
discus-identifier: filipjelic-com # disqus identifier

# Tracker
analytics: UA-47345139-1 # Google Analytics

sass:
  style: compressed

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
