title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Filip Jelic # add your name
author-img: filip-jelic.jpg # add your photo
about-author: Software engineer with a great passion for javascript. Currently working in the biotechnology industry. # add description
twitter: https://twitter.com/flipioo # add your Twitter handle
facebook: # add your Facebook handle
github: flipio # add your Github handle
linkedin: https://www.linkedin.com/in/filip-jelic-ff # add your Linkedin handle
email: jelic.filip@gmail.com # add your Email address

# Disqus
discus-identifier: flipioo # add your discus identifier

# Tracker
analytics: # Google Analytics

sass:
  style: compressed

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
