title: Filip Jelic
description: > # this means to ignore newlines until "baseurl:"
  Filip Jelic DEV blog, and everything else :)
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Author Settings
author: Filip Jelic
author-img: filip-jelic.jpg
about-author: Software engineer with a great passion for javascript. Currently working @everseen
twitter: flipioo
facebook: filip.jelic
github: flipio
linkedin: filip-jelic-ff
email: jelic.filip@gmail.com

# Disqus
discus-identifier: filipjelic-com # disqus identifier

# Tracker
analytics: UA-47345139-1 # Google Analytics

#sass:
#  style: compressed

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Resume configuration

resume_avatar:                  "true"
resume_name:                    "Filip Jelic"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jelic.filip@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+381600918818"
resume_contact_address:         ""

resume_header_contact_info:     "Belgrade • +381600918818 • jelic.filip@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a software engineer with a great passion for javascript. Currently working in the container monitoring industry. My main focus is on building scalable web apps, but you will find me building CLIs and data crunching backends on the same day.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/flipio"
  resume_twitter_url:           "http://twitter.com/flipioo"
  # resume_facebook_url:          "https://www.facebook.com/filip.jelic"
  resume_linkedin_url:          "https://www.linkedin.com/in/filip-jelic-ff"
  resume_website_url:           "https://filipjelic.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
